### ISSUE TITLE
[WONTFIX] 잘못된 주민등록번호도 통과되는 이슈

### ISSUE THREAD

**Issue by charlie-world** [Rainist/rrn#8]
input: `920827-5555555`
output: `validate: true, corresponding: false`
가 나옵니다. 

`5` 7개 넣은 것도 `validate: false` 로 가야 하지 않을까 해서 우선 등록 드립니다!

**Comment by namkwangwoo** [comment]
https://ms-office.tistory.com/7 여기 보시면 유효한 주민등록 번호 구하는 방법이 있는데

이에 따르면 `920827-5555555`는 유효한 주민등록 번호입니다.

또한 주민등록 뒷자리 첫번째 숫자는 `0~9` 모든 숫자가 올 수 있습니다.
참고) http://www.geojetimes.co.kr/news/articleView.html?idxno=54674

**Comment by charlie-world** [comment]
@Choani 아 그런가요? 실제 앞 6자리와 일치성을 따질 수 있는 방법은 없는걸까요 ?

**Comment by namkwangwoo** [comment]
실제 앞 6자리와 일치성을 따질 수 있다는 게 어떤 의미인지 잘 모르겠습니다 😭

**Comment by devholic** [comment]
@charlie-world 

외국인 등록번호의 경우 뒷자리가 5~8로 시작하게 되는데요, 현재 정확한 외국인 등록번호 체크섬 생성 로직이 공개되어있지 않아 검증할 수 없는 문제가 있습니다.
그래서 현재와 같이 숫자 여부, 생년월일만 Valid한지 판단하는 게 최선인 것 같습니다.

> 웹에서 떠돌고 있는 로직들로 구현했었는데, 외국인 등록번호 관련 문의가 들어와서 위와 같이 변경했던 걸로 기억합니다. (#3)

따라서 이 이슈에는 `bug` 라벨 대신 `wontfix` 라벨이 적절할 것 같습니다 🙂
~(라벨 수정하려고 했더니 권한이 없네용 :doge-sad:)~

**Comment by charlie-world** [comment]
고론 배경이 있었군요.....!!

**Comment by 0xd669** [comment]
제안 감사합니다. 위에 다른 분들이 말씀해주신 것과 같이 외국인등록번호의 경우 체크섬 생성 로직이 내국인과 동일하지 않아 서비스 운영 중 문제가 되었던 경우가 있었습니다. 감사합니다 :)
